name: CI/CD

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*
  pull_request:
    branches:
      - master
  # Run daily at 0:01 UTC
  schedule:
    - cron:  '1 0 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] 
    name: build olminer (${{ matrix.os }})

    steps:
    - uses: actions/checkout@master
      with:
        submodules: True
    - name: get cmake 3.19.2
      uses: lukka/get-cmake@v3.19.2
    - name: build olminer
      run: |
        mkdir -p build
        cd build
        cmake -DOLHASHCUDA=OFF ..
        ls
        cmake --build .
        ls olminer