name: CI/CD

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*
  pull_request:
    branches:
      - master
  # Run daily at 0:01 UTC
  schedule:
    - cron:  '1 0 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # , macos-latest
    name: build olminer (${{ matrix.os }})

    steps:
    - uses: actions/checkout@master
      with:
        submodules: True
    - name: get cmake 3.19.2
      uses: lukka/get-cmake@v3.19.2
    - name: build olminer
      run: |
        mkdir -p build
        pushd build
        cmake -DOLHASHCUDA=OFF ..
        cmake --build . --config Release --target package
        popd
    - name: export artifacts
      uses: actions/upload-artifact@v2
      with:
        name: olminer-executables-${{ matrix.os }}
        retention-days: 5
        path: build/olminer.*
  
